services:
  inference:
    build:
      context: .
      dockerfile: Dockerfile
    image: azani/mathchat
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - NCCL_CUMEM_ENABLE=1
    volumes:
      - ./app:/app
    working_dir: /app
    ports: 
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
